-- =====================================================================
-- Supabase Database Schema & Security Policies (RLS)
-- File: supabase_schema.sql
-- =====================================================================

-- ==========================================
-- 1. EXTENSIONS & UTILITIES
-- ==========================================
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ==========================================
-- 2. SCHEMAS & TABLES
-- ==========================================

-- 2.1 Profiles Table (Linked to Supabase Auth users)
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  full_name TEXT NOT NULL,
  phone TEXT,
  account_type INT DEFAULT 0, -- 0: Normal User, 1: Shopkeeper
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2.2 Shops Table (For Shopkeepers/Sellers)
CREATE TABLE IF NOT EXISTS public.shops (
  id UUID REFERENCES public.profiles(id) ON DELETE CASCADE PRIMARY KEY,
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  location TEXT NOT NULL,
  phone TEXT NOT NULL,
  logo_url TEXT,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 2.3 Products Table (E-commerce Items)
CREATE TABLE IF NOT EXISTS public.products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shop_id UUID REFERENCES public.shops(id) ON DELETE CASCADE NOT NULL,
  name TEXT NOT NULL,
  description TEXT,
  code TEXT,
  price NUMERIC NOT NULL CHECK (price >= 0),
  old_price NUMERIC CHECK (old_price >= 0),
  quantity INT DEFAULT 1 CHECK (quantity >= 0),
  available BOOLEAN DEFAULT TRUE,
  image_url TEXT,
  category TEXT NOT NULL,       -- Primary category (e.g., "عالم البيت", "الحياة اليومية")
  sub_category TEXT,           -- Subcategory (e.g., "مأكولات ومشروبات", "منتجات العناية")
  rating NUMERIC DEFAULT 5.0 CHECK (rating >= 0 AND rating <= 5.0),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2.4 Favorites Table (Multi-Device Wishlist)
CREATE TABLE IF NOT EXISTS public.favorites (
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  PRIMARY KEY (user_id, product_id)
);

-- 2.5 Addresses Table
CREATE TABLE IF NOT EXISTS public.addresses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  title TEXT NOT NULL, -- e.g., "المنزل", "العمل"
  city TEXT NOT NULL,
  street TEXT NOT NULL,
  phone TEXT NOT NULL,
  is_default BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2.6 Orders Table
CREATE TABLE IF NOT EXISTS public.orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  order_number TEXT UNIQUE NOT NULL,
  delivery_method TEXT NOT NULL,
  subtotal NUMERIC NOT NULL CHECK (subtotal >= 0),
  delivery_fee NUMERIC NOT NULL CHECK (delivery_fee >= 0),
  total NUMERIC NOT NULL CHECK (total >= 0),
  status TEXT DEFAULT 'قيد التنفيذ' NOT NULL, -- 'قيد التنفيذ' (Pending), 'مكتمل' (Completed), 'غير مكتمل' (Failed/Incomplete)
  address_id BIGINT REFERENCES public.addresses(id) ON DELETE SET NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2.7 Order Items Table
CREATE TABLE IF NOT EXISTS public.order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT REFERENCES public.orders(id) ON DELETE CASCADE NOT NULL,
  product_id BIGINT REFERENCES public.products(id) ON DELETE SET NULL,
  price NUMERIC NOT NULL CHECK (price >= 0),
  quantity INT NOT NULL CHECK (quantity > 0)
);

-- 2.8 Exchange Items Table (For barter/item exchange posts)
CREATE TABLE IF NOT EXISTS public.exchange_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  category TEXT NOT NULL,
  image_url TEXT,
  expected_exchange TEXT, -- What user wants in barter
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2.9 Donations Table (Monetary or physical items)
CREATE TABLE IF NOT EXISTS public.donations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  title TEXT NOT NULL,
  amount NUMERIC CHECK (amount >= 0),
  type TEXT NOT NULL, -- "money", "items"
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2.10 Chats Table (Conversation Headings)
CREATE TABLE IF NOT EXISTS public.chats (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  shop_owner_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE (user_id, shop_owner_id)
);

-- 2.11 Messages Table
CREATE TABLE IF NOT EXISTS public.messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  chat_id UUID REFERENCES public.chats(id) ON DELETE CASCADE NOT NULL,
  sender_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL NOT NULL,
  text TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ==========================================
-- 3. TRIGGERS & FUNCTIONS
-- ==========================================

-- Function to handle new user registration from Supabase Auth
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, phone, account_type)
  VALUES (
    new.id,
    COALESCE(new.raw_user_meta_data->>'full_name', ''),
    COALESCE(new.raw_user_meta_data->>'phone', ''),
    COALESCE((new.raw_user_meta_data->>'account_type')::int, 0)
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger to execute on signup
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ==========================================
-- 4. ROW LEVEL SECURITY (RLS) POLICIES
-- ==========================================

-- Enable Row Level Security (RLS) on all tables
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.shops ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.favorites ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.addresses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.exchange_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.donations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chats ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;

-- 4.1 Profiles Policies
CREATE POLICY "Allow public read access to profiles" ON public.profiles
  FOR SELECT USING (true);

CREATE POLICY "Allow authenticated users to update their own profile" ON public.profiles
  FOR UPDATE USING (auth.uid() = profiles.id);

-- 4.2 Shops Policies
CREATE POLICY "Allow public read access to shops" ON public.shops
  FOR SELECT USING (true);

CREATE POLICY "Allow owners to insert/update their shop info" ON public.shops
  FOR ALL USING (auth.uid() = shops.id);

-- 4.3 Products Policies
CREATE POLICY "Allow public read access to products" ON public.products
  FOR SELECT USING (true);

CREATE POLICY "Allow shop owners to manage their products" ON public.products
  FOR ALL USING (
    auth.uid() IN (SELECT shops.id FROM public.shops WHERE shops.id = products.shop_id)
  );

-- 4.4 Favorites Policies
CREATE POLICY "Allow users to view their own wishlist" ON public.favorites
  FOR SELECT USING (auth.uid() = favorites.user_id);

CREATE POLICY "Allow users to manage their own wishlist" ON public.favorites
  FOR ALL USING (auth.uid() = favorites.user_id);

-- 4.5 Addresses Policies
CREATE POLICY "Allow users to view their own addresses" ON public.addresses
  FOR SELECT USING (auth.uid() = addresses.user_id);

CREATE POLICY "Allow users to manage their own addresses" ON public.addresses
  FOR ALL USING (auth.uid() = addresses.user_id);

-- 4.6 Orders Policies
CREATE POLICY "Allow users and corresponding shopkeepers to view orders" ON public.orders
  FOR SELECT USING (
    auth.uid() = orders.user_id OR
    auth.uid() IN (
      SELECT s.id 
      FROM public.shops s 
      JOIN public.products p ON p.shop_id = s.id
      JOIN public.order_items oi ON oi.product_id = p.id
      WHERE oi.order_id = orders.id
    )
  );

CREATE POLICY "Allow authenticated users to create orders" ON public.orders
  FOR INSERT WITH CHECK (auth.uid() = orders.user_id);

CREATE POLICY "Allow corresponding shopkeepers to update order status" ON public.orders
  FOR UPDATE USING (
    auth.uid() IN (
      SELECT s.id 
      FROM public.shops s 
      JOIN public.products p ON p.shop_id = s.id
      JOIN public.order_items oi ON oi.product_id = p.id
      WHERE oi.order_id = orders.id
    )
  );

-- 4.7 Order Items Policies
CREATE POLICY "Allow users and corresponding shopkeepers to view order items" ON public.order_items
  FOR SELECT USING (
    auth.uid() IN (SELECT orders.user_id FROM public.orders WHERE orders.id = order_items.order_id) OR
    auth.uid() IN (
      SELECT s.id 
      FROM public.shops s 
      JOIN public.products p ON p.shop_id = s.id
      WHERE p.id = order_items.product_id
    )
  );

CREATE POLICY "Allow authenticated users to insert order items" ON public.order_items
  FOR INSERT WITH CHECK (
    auth.uid() IN (SELECT orders.user_id FROM public.orders WHERE orders.id = order_items.order_id)
  );

-- 4.8 Exchange Items Policies
CREATE POLICY "Allow public read access to exchange posts" ON public.exchange_items
  FOR SELECT USING (true);

CREATE POLICY "Allow owners to manage their exchange posts" ON public.exchange_items
  FOR ALL USING (auth.uid() = exchange_items.user_id);

-- 4.9 Donations Policies
CREATE POLICY "Allow users to view their own donations" ON public.donations
  FOR SELECT USING (auth.uid() = donations.user_id);

CREATE POLICY "Allow users to insert donations" ON public.donations
  FOR INSERT WITH CHECK (auth.uid() = donations.user_id);

-- 4.10 Chats Policies
CREATE POLICY "Allow participants to view their chat history" ON public.chats
  FOR SELECT USING (auth.uid() = chats.user_id OR auth.uid() = chats.shop_owner_id);

CREATE POLICY "Allow participants to create chat threads" ON public.chats
  FOR INSERT WITH CHECK (auth.uid() = chats.user_id OR auth.uid() = chats.shop_owner_id);

-- 4.11 Messages Policies
CREATE POLICY "Allow chat participants to view messages" ON public.messages
  FOR SELECT USING (
    auth.uid() IN (
      SELECT chats.user_id FROM public.chats WHERE chats.id = messages.chat_id
      UNION
      SELECT chats.shop_owner_id FROM public.chats WHERE chats.id = messages.chat_id
    )
  );

CREATE POLICY "Allow chat participants to send messages" ON public.messages
  FOR INSERT WITH CHECK (
    auth.uid() = messages.sender_id AND
    auth.uid() IN (
      SELECT chats.user_id FROM public.chats WHERE chats.id = messages.chat_id
      UNION
      SELECT chats.shop_owner_id FROM public.chats WHERE chats.id = messages.chat_id
    )
  );

-- ==========================================
-- 5. STORAGE BUCKET CONFIGURATION & POLICIES
-- ==========================================

-- Create storage buckets for uploads
INSERT INTO storage.buckets (id, name, public)
VALUES 
  ('product-images', 'product-images', true),
  ('shop-logos', 'shop-logos', true),
  ('exchange-images', 'exchange-images', true)
ON CONFLICT (id) DO NOTHING;

-- 5.1 Public Read Policies for Storage Buckets
CREATE POLICY "Allow public read access to product images" ON storage.objects
  FOR SELECT USING (bucket_id = 'product-images');

CREATE POLICY "Allow public read access to shop logos" ON storage.objects
  FOR SELECT USING (bucket_id = 'shop-logos');

CREATE POLICY "Allow public read access to exchange images" ON storage.objects
  FOR SELECT USING (bucket_id = 'exchange-images');

-- 5.2 Upload/Delete Policies for Authenticated Users
CREATE POLICY "Allow authenticated users to upload product images" ON storage.objects
  FOR INSERT WITH CHECK (
    bucket_id = 'product-images' AND auth.role() = 'authenticated'
  );

CREATE POLICY "Allow authenticated users to upload shop logos" ON storage.objects
  FOR INSERT WITH CHECK (
    bucket_id = 'shop-logos' AND auth.role() = 'authenticated'
  );

CREATE POLICY "Allow authenticated users to upload exchange images" ON storage.objects
  FOR INSERT WITH CHECK (
    bucket_id = 'exchange-images' AND auth.role() = 'authenticated'
  );

CREATE POLICY "Allow authenticated users to delete their own product images" ON storage.objects
  FOR DELETE USING (
    bucket_id = 'product-images' AND auth.role() = 'authenticated' AND (owner = auth.uid())
  );

CREATE POLICY "Allow authenticated users to delete their own shop logos" ON storage.objects
  FOR DELETE USING (
    bucket_id = 'shop-logos' AND auth.role() = 'authenticated' AND (owner = auth.uid())
  );

CREATE POLICY "Allow authenticated users to delete their own exchange images" ON storage.objects
  FOR DELETE USING (
    bucket_id = 'exchange-images' AND auth.role() = 'authenticated' AND (owner = auth.uid())
  );
